import React, { useState, useEffect } from 'react';
import './timings.css';
import "aos/dist/aos.css";
import AOS from 'aos';
const Timings = () => {
  const [massageType, setMassageType] = useState('');
  const [date, setDate] = useState('');
  const [time, setTime] = useState('');
  const [persons, setPersons] = useState('');
  const [name, setName] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [message, setMessage] = useState('');

  const daysandtimings = {
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
  };

  const [minDate, setMinDate] = useState('');

  useEffect(() => {
    const now = new Date();

    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');

    var minD = year+'-'+month+'-'+day;
    setMinDate(minD);

  }, []);

  useEffect(() => {
    AOS.init({
      disable: "phone",
      duration: 1000,
      easing: "ease-out-cubic",
    });
  }, []);

  const handleSubmit = () => {
    const whatsappNumber = '9831626569';
    const whatsappMessage = `
      Massage Type: ${massageType}
      Date: ${date}
      Time: ${time}
      Persons: ${persons}
      Name: ${name}
      Phone Number: ${phoneNumber}
      Message: ${message}

      Auto Message generated by Vynapse
    `;
    const whatsappLink = `https://api.whatsapp.com/send?phone=${whatsappNumber}&text=${encodeURIComponent(whatsappMessage)}`;
    window.open(whatsappLink, '_blank');
  };

  return (
    <div className="spa__timings" id="contacts">
      <div className="spa__timings-information" data-aos="fade-left">
        <h1 style={{color: "var(--color-highlight)"}}>Opening Hours</h1>
        <p>A collection of textile samples lay spread out on the table Samsa was a travelling salesman.</p>
        <ul>
          {daysandtimings.days.map((day, i) => (
            <li key={i}>{day}: 11 A.M. to 9.30 P.M.</li>
          ))}
        </ul>
      </div>

      <form className='spa__timings-form' onSubmit={(e) => e.preventDefault()} data-aos="fade-right">
        <h2>Book your appointment</h2>
        <select required onChange={(e) => setMassageType(e.target.value)} value={massageType}>
          <option value="" disabled>Select Massage Type</option>
          <option value="Thai Dry">Thai Dry</option>
          <option value="Balinese">Balinese</option>
          <option value="Swedish Massage">Swedish Massage</option>
          <option value="Aroma Therapy">Aroma Therapy</option>
          <option value="Deep Tissue Therapy">Deep Tissue Therapy</option>
          <option value="Romantic Indulgence">Romantic Indulgence</option>
        </select>
        <div className="spa__timings-form-dtp">
          <input type="date" required onChange={(e) => setDate(e.target.value)} value={date} min={minDate}/>
          <input type="time" required onChange={(e) => setTime(e.target.value)} value={time} />
          <select required onChange={(e) => setPersons(e.target.value)} value={persons}>
            <option value="" disabled>Number of Persons</option>
            <option value="1 Person">1 Person</option>
            <option value="2 Persons">2 Persons</option>
            <option value="3 Persons">3 Persons</option>
          </select>
        </div>
        <div className="spa__timings-form-details">
          <label>Name</label>
          <input type="text" required onChange={(e) => setName(e.target.value)} value={name} />
        </div>
        <div className="spa__timings-form-details">
          <label>Phone Number</label>
          <input type="number" required onChange={(e) => setPhoneNumber(e.target.value)} value={phoneNumber} />
        </div>
        <div className="spa__timings-form-details">
          <label>Message</label>
          <textarea type="text" required onChange={(e) => setMessage(e.target.value)} value={message}></textarea>
        </div>
        <div className="button" onClick={handleSubmit}>
          <p>Submit</p>
        </div>
      </form>
    </div>
  );
};

export default Timings;
